### ISSUE TITLE
Learning BBB, JavaScript, node.js, etc... 

### ISSUE THREAD

**Issue by badfrogg** [badfrogg/BBB_Aquarium#1]
Right now I need to learn the very basics of running a program on the BeagleBone Black
The current set up is:
BeagleBone Black Ver. C
Linux 9 (Stretch)
Debian Image 2018-06-17
Linux BeagleBone 4.14.52-ti-r60

The first thing I would like to do is have control of the PWM output pins and get a basic program to run when the board is started. I would also like to have a UI of some kind. Either just a console or web UI so that I can interact and see the change. The board PWM pin P9-16 (GPIO51) is connected to an oscilloscope for now. Wont be building any hardware until i have the basic software running.

**Comment by silver2row** [comment]
Hello...you have found help. I accepted your invite. 

Hey sir, you are lucky. I have some books that we can use.

Seth

**Comment by silver2row** [comment]
Hey...Seth here,

Okay. PWM w/ JavaScript/Node.js is out of my range right now but using it w/ Python should be straight forward. 

…

I am going to try to add some software to your repo here on GitHub.com. We can try in many different languages until you find what hinges you the right way.

Seth

P.S. If you do not want to test the language of Python or Node.js for some reason, mostly b/c I have a difficult time describing things, we can always have me test things first and I can then report my findings.

**Comment by badfrogg** [comment]
Python is fine for me. I only have experience in c++. So learning Python will be no different then learning JS. its all going to be new stuff.

**Comment by silver2row** [comment]
Here are some books to view:

- Node Web Development 2nd Edition (Ch. 4 p. 81)

- Mastering Node.js (Ch. 6 p. 164)

I found this software. Try it out and run it w/ node.js <file name>. If that does not work, you can try to use the sudo cmd.

Seth...

P.S. Here is the software.
    <!DOCTYPE html> 
    <html> 
    <head> 
    <title> Introduction to JavaScript </title> 
    <script type="text/javascript">  
      alert(" Welcome to Packt "); 
    </script> 
    </head> 
    </html>

...and w/ JavaScript (all while running it w/ node on our BBBs)

    <!DOCTYPE html> 
    <html> 
    <head> 
    <title> Introduction to JavaScript </title> 
    <script type="text/javascript" src="main.js"></script> 
    </head> 
    </html>

Here is the difference b/t the HTML and HTML w/ JavaScript.

**Comment by silver2row** [comment]
Hello Sir,

So...you can use Python, too. I know you say you are just learning but C++ is way more difficult. Python should come to you easily.

Here: https://github.com/adafruit/adafruit-beaglebone-io-python. I have used that library over and over again. If you want to set up PWM on a BBB, that library should be easy and no-nonsense. 

Seth

P.S. So, PWM w/ Python. Please hold on and I will test out the PWM software on something until I can get that hardware you have listed on the main page.

**Comment by badfrogg** [comment]
Sure. I'm am not to worried about writing the software. What I need right now is the physical computing stuff.
How about this: This program is copied right from the BeagleBone BoneScript web page
`var b = require('bonescript');
b.analogWrite('P9_14', 0.7, 2000, printJSON);
function printJSON(x) { console.log(JSON.stringify(x)); }`

This should make the P9-14 pin output PWM at 2kHz and a duty cycyle of 70%
So I can copy this code into a file that i call PWMtest.js and then the the prompt
`$ node PWMtest.js`

I can do that much and it works. I see it on my oscilloscope. 

What i want to do next is to be able to send a command to that program to manipulate the duty cycle in runtime. "set duty to 0.5" for example to set the duty to 50%

I also want to understand how to make this program run when the board boots.

**Comment by badfrogg** [comment]
Ok let me work on that for a bit.
BTW dont worry about the hardware outside of the BBB. That stuff I already know. Its the hardware software interface between the program running and the GPIO pins that I need to be fully proficient.

**Comment by silver2row** [comment]
Hello,

I usually take an entirely different approach when attempting to perform software/hardware related functionality.

I usually take my hardware and find a way to make it work via software. You can teach me something different. I am sure of it now but...

1. I am working on some software now.
  a. I am going to have to learn more.
  b. I am going to use Python, Flask, and HTML. 
  c. If we want to add some JavaScript into the HTML, we can. 

2. If this is for production ideas, we will need to go your route most likely.
  a. Flask is not for production.
  b. This means, I will have to learn more than I thought.

I am going to add some software for Flask to get us up to speed on Servers, HTML pages, and additions that can be made to the existing software.

Seth

P.S. Okay...so, here goes nothing.

**Comment by silver2row** [comment]
I added a new bunch of software. If you need to have examples and ideas revolve around it, let me know.

Seth

**Comment by silver2row** [comment]
The idea here is to make sure our, your, timer is set at the right time throughout time presently.

So, if the Sun rises at 6:15 and the Sun sets at 8:30, the timer needs to be able to keep up w/ this idea of rise/fall.

I have not really figured this out yet. 

…

sudo dpkg-reconfigure tzdata

This cmd will help us, you, set up times and then we can worry about dates later.

Seth

**Comment by silver2row** [comment]
Oh Yea Sir,

We do not need to put every bit of software in one file. I keep forgetting. Sorry.

Seth

**Comment by silver2row** [comment]
Hello,

Does your x11 Desktop work for your BBB?

Seth

**Comment by silver2row** [comment]
Hello Once More,

raw_input in Python can help us if necessary. I see you do not like those copies of other files from books I have read, i.e. w/ a bit of pizazz. 

Seth

P.S. I can look up how to use it again if you are looking to have scripts perform w/ user input.

**Comment by silver2row** [comment]
Look at my funny software for the Hour issue...

Seth

**Comment by badfrogg** [comment]
Seth. I appreciate your help. please keep it coming. I'm not really able to follow the code that you have sent. I guess that I've already gone far enough down the JavaScript/Node.js route that I dont want to start over with Python.

I'm also not a very good multitasker. Right now I'just focused on the PWM hardware/drivers and a console interface to control it (See the TestPWM.js). once I have that working reliably then I will focus on the software.

**Comment by silver2row** [comment]
@badfrogg ...

You are way ahead of me on this idea for now. My code is just for fun right now. I will keep trying.

Seth

**Comment by badfrogg** [comment]
Yes please enjoy. If you know anyone else that might like to contribute please feel free to show them this project. It will be opensource and free. Not production.

**Comment by silver2row** [comment]
Hello,

I found this one person online that wanted to help one day. See here: https://github.com/silver2row/pyBot.

I know that it is my account but that software was used and typed up by that HN-Vignolles person. I do not know that person all that well but that person may prove valuable in your efforts.

Seth

P.S. I will check back periodically to check in and add new software to my "patches."

**Comment by badfrogg** [comment]
Thanks. I did make a breakthrough today. I have uploaded two files thatwork together "PWM_Server.js" and "PWM.html"
Running PWM_Server allows you to browse in with a web browser and manipulate the PWM pin on the BBB. 

There are still some funny behaviors. Running the program once will through an error that the PWM Period was not set and defults to 500000ns (or 2kHz). running it twice will work though. Weird.

**Comment by silver2row** [comment]
Hello...

You have blown me away here. First, you say you do not know much and you are just starting out. Then, you accomplish all these tasks w/out help. You must be one, smart fellow.

Seth

P.S. I have not gotten to doing more just yet. I will keep you updated.

**Comment by silver2row** [comment]
@badfrogg 

About that PWM setting, you can set all the PWM settings on one line if necessary (I think). I guess it depends on which library you are using.

Seth

**Comment by silver2row** [comment]
Hey man...Seth here...

I feel as though you beat me. You found out too much too quickly. My process is a bunch slower. Seriously.

Anyway, I am happy you have done good by making your software run. @badfrogg 

If something comes up and you need some additional support on a specific item, esp. if you get too frustrated w/ the current software, let me know and I will gear my mind towards one task.

But for real, you have done well.

Seth

P.S. Let a brother know if you need anything. I have stopped promoting the Flask microframework for Python for now. I can pick up later if necessary.

**Comment by badfrogg** [comment]
Thanks Seth. I am still just fumbling my way through this. This whole approach is not the way I like to do things, Just throwing stuff at the wall and seeing what sticks. I like to have that cornerstone understanding of what I'm working on so that I am building knowledge up from a solid foundation. However. some things are starting to make sense so that's good. I am going to move forward right now with the BoneScript library and Node.js since that is what the BeagleBone creators seem to be promoting the most.

**Comment by silver2row** [comment]
Hello @badfrogg ,

Seth here. I see you are working from the book I own. I have that book. Maybe I can look now and see where we/you are making mistakes.

Seth

P.S. I tried to get the LED lit on my side w/ that software yesterday. I was unsuccessful. I think I have unmet dependencies or something. I will keep you updated.

**Comment by silver2row** [comment]
@badfrogg ,

Seth here again. Okay, I am up and running w/ Node.js, JavaScript, BoneScript, and HTML on an onboard LED for now.

I will keep testing. I see where the fellow changed the port on where we host the application. This was my issue.

Seth

P.S. 8085 is the port to choose for me for now.

**Comment by silver2row** [comment]
@badfrogg ...where would you put me to work if you were to put me to work for now? Do you need help in any particular setting?

Seth

**Comment by badfrogg** [comment]
I could use help understanding Linux a little better. I want to understand how to get this simple preliminary code to run at boot. I would also like to know why this program throws errors sometimes. I thing it has to do with permissions but I just dont know enough to understand. The Node.js "BoneScript" Library calls the function "analogwrite()" and passed the data for pin, duty and period. Maybe this library is somewhat broken or bugged because it doesn't always work.

**Comment by badfrogg** [comment]
So are you running a BeagleBone Black? Oh, and yes, the port is 8085. I will try to keep the README up to date with the latest working environment. Ill add that note.

**Comment by silver2row** [comment]
use sudo before your command. I know at times people say that sudo is not needed but at times, it may be this simple.

for instance...

    sudo node pwmServer.js

or...

    sudo nodejs pwmServer.js

and so on...

Does this almost make sense?

Okay. I am going to make a pastebin.com paste and add it to this repo for using services to run software on boot. 

Sort of...I have the BBBW. It is the wireless version. 

Seth

P.S. The pastebin may be just a photo on this board. I can select the photos to add if necessary.

**Comment by silver2row** [comment]
Hello,

W/ your filesystem in Linux, the BBB.io people's distro, go to /lib/systemd/system directory. In this directory, make a file called:

    PWM_Server.service

...

Use nano or your favorite editor. Once in that file, which should be blank, type in the below requirements for setting up a .service file in a systemd environment. Oh and use this cmd for your file PWM_Server.js.

    sudo chmod a+x PWM_Server.js

That cmd will in turn set that file to be an executable.

This is your .service file. You can find more on this at https://learn.adafruit.com/running-programs-automatically-on-your-tiny-computer?view=all#systemd-writing-and-enabling-a-service and here at https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units.

    [Unit]
    Description=Server for Light with PWM
 
    [Service]
    ExecStart=/home/debian/PWM_Server.js
    StandardOutput=null
 
    [Install]
    WantedBy=multi-user.target
    Alias=PWM_Server.service

and...

to enable this service, use these cmds:

    sudo systemctl enable PWM_Server.service

    sudo systemctl start PWM_Server.service

Seth

P.S.

**Comment by badfrogg** [comment]
OK, I didnt quite understand clearly your instructions but I am reading the link you included.
Is ```sudo chmod a+x PWM_Server.js``` the only line that should be in the "PWM_Server.service
" file?
is
```
[Unit]
Description=Server for Light with PWM

[Service]
ExecStart=/home/debian/PWM_Server.js
StandardOutput=null

[Install]
WantedBy=multi-user.target
Alias=PWM_Server.service
```
 also supposed to be included in that fire ?

**Comment by silver2row** [comment]
Hello Again,

I keep forgetting that you want to know the background on these subjects, e.g. .service files, running a service, software ideas, and etc...

I will take some time out and make sure I get this idea rounded off and completed before I type up "willy-nilly" ideas on what I have learned. Most of this stuff is review but things change, ideas fade, and my memory gets bogged down. So, I will do better next time.

Seth

**Comment by silver2row** [comment]
Hello,

For now...forget the service. I need to work on it more. I went into the #beagle chat on Freenode and inquired about the .service files. I got upended by a person that knew more than me.

Seth

**Comment by silver2row** [comment]
Hello...my .js and .html file no longer produce the desired result. 

I am not sure what happened from yesterday to today but the program does not work for me.

Seth

P.S. I will keep trying to fix things but this may be a lost cause. Do your files still work out to the desired result?

**Comment by badfrogg** [comment]
I've had to stop working on it the last few days. I will double check the version here with what I have been running and testing. I may have pushed a broken version to git accidentally.

**Comment by silver2row** [comment]
Hello,

I was actually testing another software example from the same book to check my .service files. 

Since the software stopped working, I have been unable to test the .service files so I can finally explain what I did. 

Seth

P.S. I should have time tonight. After getting the software up and running again, I will make my .service files and then explain how I got all the files to work. What should work w/ the example I am using should also work w/ your example.

**Comment by silver2row** [comment]
Hello...

@badfrogg 

Here:

    
![dafrog](https://user-images.githubusercontent.com/9708195/42669379-b211dd38-861a-11e8-9f46-fe9230fd3bb0.PNG)

Where is says **secondcontrol.js**

...

Use your file name that you want to run. 

Then...

Use these cmds in the directory /etc/systemd/system where you will make your service file. My service file was called secondcontrol.service.

    sudo systemctl enable secondcontrol.service

    sudo systemctl start secondcontrol.service

Reboot and try the web address w/ the :8085 ending for the port.

Seth

**Comment by silver2row** [comment]
First,

Hello again. Second...try to run that software w/out running the application on your terminal.

Seth

P.S. 192.168.7.2:8085

**Comment by badfrogg** [comment]
Thanks for all your efforts. I have been studying "systemd" and these "services.d" files as they are called. this is certainly not a trivial subject and it quite hard to understand from a new Linux user perspective. The Debian image that comes with the Beaglebone Black has several .js services + HTML running that are built into the "out of the box" image. They got those running somehow...

**Comment by silver2row** [comment]
Yes Sir,

They put together, what I think is called, a starter script. If you go to 192.168.7.2:3000 on Chrome or Firefox, you can log into your BBB and browse. 

On the lefthand side of the display, there is a file system w/ a file called autorun. If you place your files in that directory, you can run .js files on boot.

I think this file, that .js file from Monk and his book and even after w/ GitHub listings w/ updates, cannot run completely, 100% of the time. B/c of this issue, the .service file would not have access to that file running as a server. This is the issue. I think the starter script or .service file is okay. Testing will ensue. Let me know if you find anything out about this file. I think it is a "global" file in the sense that the software is supposed to work globally and not locally. Local files are different. W/ a local file, from what little I can grasp for now, is supposedly run w/ local variables and not global variables. 

The local variable, I am pretty sure, would be like running local servers from your computer or on an isolated target board, e.g. the BBB. 

Seth

P.S. If I am wrong and this is silly, I am sorry. I may have read this terminology incorrectly. Again, more testing will ensue. For instance, I run my server(s) on 192.168.7.2:xxxx. If this makes sense, good. Outside of this effort, the .js file needs to have this isolated location available, e.g. IP Address plus Port. On Monk's software example, his server(s) have no effort towards this idea. 'connection' cannot be changed to a local IP Address for some reason. I have not figured it out yet.

**Comment by silver2row** [comment]
Hello Sir,

Here is another good resource for .service files: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Examples.

Seth

**Comment by badfrogg** [comment]
Thanks a million Seth. Lets take a short break this from this. I will be installing the computer (ECU) for my Turbo Subaru Legacy Wagon this weekend, (Some thing I know how to do well BTW). I need to do some thing fun right now. Linux is not fun!

**Comment by silver2row** [comment]
Hello,

No issue. If I come up w/ something, I will take a break and then let you know something. Linux can be frustrating, just like that big fish that cannot be caught. 

Seth

P.S. I will wait to hear from you another day. Not an issue at all...says me.

**Comment by silver2row** [comment]
Hello Sir,

Seth here. I found that the dependencies for socket.io are out of date. I went to their gitHub.com page and saw that on one of their headings.

Seth

P.S. I have not gotten back to it yet. I just wanted to let you know.

**Comment by badfrogg** [comment]
I am using socket.io 2.1.1 None of its regular dependencies are out of date. It dose have some devDependencies that are out of date but that is not going to effect a regular user of the library. (As far as I know).
By the way, I still have not touched this protect in the last week. I have a big project for work right now and I'm spending y spear time to finish my car project at the moment.

**Comment by silver2row** [comment]
Hello @badfrogg ,

Seth here. I will add this idea b/c you were learning GitHub/Git stuff at first. I do not know where you are on taking more dives into Linux and JavaScript for now but look here: https://www.git-scm.com/book/en/v2/Getting-Started-About-Version-Control.

Seth

P.S. It is a free book dedicated to git versioning control. It works w/ GitHub.com.

**Comment by silver2row** [comment]
@badfrogg ,

Sir...look here: https://github.com/silver2row/bbg. I started a repo for the Motor Bridge Cape but I have added some temp. files for maybe adding them later.

Oh and look at time.py and templates/main.html. If you run the time.py file w/ sudo python time.py, you will see the info. on a webpage.

But...you need to have the templates directory and a matching file, e.g. namely main.html in that directory.

Seth

P.S. If you get bored, try it out. It may prove valuable on your journey for starters.

**Comment by badfrogg** [comment]
Thanks Seth. I will check it out.

**Comment by silver2row** [comment]
Hello...

@badfrogg , I figured out, through lessons upon lessons and trial and error, while listening to someone on Freenode how to actually make photos on .html files a reality on my Flask servers.

Anyway...

If you need a tree of my directories, let me know. You can see a funny photo, an odd webpage, and a steady state of "shareable" context via an online web page.

Seth

P.S. Well...here is the tree for now:

    .
    ├── static
    │   └── images
    │       └── openFile.jpg
    ├── templates
    │   ├── mainOne.html
    │   └── mainTwo.html
    ├── timeIII.py
    ├── timeII.py
    └── time.py

**Comment by silver2row** [comment]
Hello Again...

Oh and there is someone that might need credit for this {{ time }} section of the flask application. I just cannot remember where I picked it up. If I come across it again, I will update you on who did what and when.

Seth

P.S. You can find that above tree and related files at bbg or https://github.com/silver2row/bbg.

**Comment by silver2row** [comment]
Hello Once More,

I found this software interface and ideas on YouTube.com here: https://www.youtube.com/watch?v=406nG-m-iz0&feature=youtu.be. 

This may help in your journey. If you ever want to rehash the experience, let me know. 

Seth

**Comment by silver2row** [comment]
Hello,

I am still working on Flask, Python, and the BBB w/ applications and HTML sites online. If you get bored and want to try again, look here at a Socket/Python framework: https://realpython.com/python-sockets/.

Seth

P.S. I just found it by searching my inbox. Anyway...I hope things are going well w/ your updates and Linux. See you later for now.

**Comment by badfrogg** [comment]
Thanks Seth. I am holding off at the moment with this project. I am in the busy season at work. Probably be back on it in October. I will take a lok at your links though, Thanks!

**Comment by silver2row** [comment]
No issue. I will hopefully hear from you then. Until then, enjoy and Linux!

Seth

**Comment by silver2row** [comment]
@badfrogg ,

Sir, did you ever get back on w/ the Linux gig and ideas relating to this post? Look here, sir: https://github.com/silver2row/motocape.

That controls two motors, e.g. forward, left, right, and stop w/ the new MotorCape from BBB.io people.

...

Seth

P.S. We can probably use it to support your cause. I think I have some kinks worked out. I received some input and help but in the end, I put in some work and got the idea "completed." It is still a work in progress.

**Comment by silver2row** [comment]
@badfrogg ,

Sir...I have not heard from you. Oct. is around the corner!

Seth

P.S. I will keep trying to stay patient.
